/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.config.DatabaseConnection;

public class App {

    public static void main(String[] args) {
        DatabaseConnection.getConnection();
    }
}
